### ISSUE TITLE
Add 'recommonmark' to rtfd org

### ISSUE THREAD

**Issue by ericholscher** [lu-zero/remarkdown#2]
Hi,

I'm thinking about adding recommonmark to the Read the Docs organization on GitHub (rtfd) -- where we would plan to maintain official support for it on Read the Docs. Would be okay with you if that became the main place for development? Currently I have a fork that is getting a few contributions (https://github.com/ericholscher/recommonmark/pulls), but I'd like to have an obvious "home".

I'd happily list you as the primary author, and give you admin/commit on the org repo. The other option would be to have you create a 'recommonmark' repo under your account and use that as the official, but perhaps without the forking metadata, so it's obviously the "home" repo.

Thoughts?

**Comment by lu-zero** [comment]
I'd be really happy to have it in read the docs organization!

I hope this way we can get more people involved so we can progress quickly to get an alternative markup for sphinx =)

Go for it =)

**Comment by ericholscher** [comment]
Great! We're definitely hoping to get it wider adoption, and have markdown become a first class supported option :)

**Comment by ericholscher** [comment]
The new repo is now created: https://github.com/rtfd/recommonmark

You should have an invite to the org, which will give you commit on the repo.

**Comment by lu-zero** [comment]
Perfect! You caught me when I was eating out =)

**Comment by ericholscher** [comment]
:fireworks:
